config/routes.rb
Rails.application.routes.draw do
  resources :pedidos
  root 'main#login'
  resources :produtos
  resources :fornecedores
  resources :clientes
  get 'main/login'
  get 'main/index'
  get '/login', :to => redirect('main/login')
  get '/index', :to => redirect('main/index')
  get 'main/verifica_usuario'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cliente.rb
class Cliente < ApplicationRecord
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente criado com sucesso.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:codigo, :razaoSocial, :cnpj)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @cliente.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h4>

      <ul>
      <% @cliente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label class="col-sm-2 control-label" for="cliente_codigo">Código</label>
    <div class="col-sm-10">
      <%= f.number_field :codigo, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label" for="cliente_razaoSocial">Razão social</label>
    <div class="col-sm-10">
      <%= f.text_field :razaoSocial, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-2 control-label" for="cliente_cnpj">CNPJ</label>
    <div class="col-sm-10">
      <%= f.text_field :cnpj, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary", value: "Salvar cliente", 'data-disable-with': "Salvando cliente" %>
    </div>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<div class="page-header">
  <%= link_to clientes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to @cliente, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Exibir
  <% end %>
  <h1>Editando cliente</h1>
</div>

<%= render 'form' %>

app/views/clientes/index.html.erb
<div class="page-header">
  <%= link_to new_cliente_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Novo cliente
  <% end %>
  <h1>Lista dos clientes</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Código</th>
        <th>Razão social</th>
        <th>CNPJ</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @clientes) do |cliente| %>
            <td><%= cliente.codigo %></td>
            <td><%= cliente.razaoSocial %></td>
            <td><%= cliente.cnpj %></td>
            <td><%= link_to 'Exibir', cliente %></td>
        <td><%= link_to 'Editar', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Deletar', cliente, method: :delete, data: { confirm: 'Tem certeza disso?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/clientes/new.html.erb
<div class="page-header">
  <%= link_to clientes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h1>Novo cliente</h1>
</div>

<%= render 'form' %>

app/views/clientes/show.html.erb
<div class="page-header">
  <%= link_to clientes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to edit_cliente_path(@cliente), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h1>Exibir cliente</h1>
</div>

<dl class="dl-horizontal">
  <dt>Código:</dt>
  <dd><%= @cliente.codigo %></dd>

  <dt>Razão social:</dt>
  <dd><%= @cliente.razaoSocial %></dd>

  <dt>CNPJ:</dt>
  <dd><%= @cliente.cnpj %></dd>

</dl>