config/routes.rb
Rails.application.routes.draw do
  resources :pedidos
  root 'main#login'
  resources :produtos
  resources :fornecedores
  resources :clientes
  get 'main/login'
  get 'main/index'
  get '/login', :to => redirect('main/login')
  get '/index', :to => redirect('main/index')
  get 'main/verifica_usuario'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def login

  end

  def index

  end

  def verifica_usuario
    username = params[:username].to_s
    password = params[:password].to_s

    account = Account.find_by(:username => username, :password => password)

    user_exists = !account.nil?

    respond_to do |format|
      format.html
      format.json { render json: {user_exists: user_exists} }
    end
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/index.html.erb
<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
  <head>
    <title>Pagina Principal</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css" type="text/css"/>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </head>
  <body>
    <div class="panel panel-primary">
      <div class="panel-heading">RD Controle de Estoque</div>
      <div class="panel-body">
        <div class="row">
          <div class="col-sm-2">
            <div class="panel panel-default">
              <div class="panel-body">
                <%= image_tag("magic.png", class: "img-rounded", alt: "Chapéu", width: "100%", height: "100%") %>

              </div>
            </div>

          </div>
          <div class="col-sm-10">
            <div class="panel panel-default">
              <div class="well" id="usuarioWell">Seja bem-vindo!</div>

              <div class="row">

                <div class="col-sm-3" >
                  <div class="panel panel-default">
                    <%= image_tag("produtos 3.png", class: "center-block", alt: "fornecedor", width: "50%") %>
                    <%= link_to("Fornecedores", fornecedores_path, type: "button", class:"btn btn-primary btn-block") %>
                  </div>
                </div>

                <div class="col-sm-3">
                  <div class="panel panel-default">
                    <%= image_tag("produtos 4.png", class: "center-block", alt: "produtos", width: "50%") %>
                    <%= link_to("Produtos", produtos_path, type: "button", class:"btn btn-primary btn-block") %>
                  </div>
                </div>

                <div class="col-sm-3">
                  <div class="panel panel-default">
                    <%= image_tag("cliente.png", class: "center-block", alt: "cliente", width: "50%") %>
                    <%= link_to("Clientes", clientes_path, type: "button", class:"btn btn-primary btn-block") %>
                  </div>
                </div>

                <div class="col-sm-3">
                  <div class="panel panel-default">
                    <%= image_tag("produtos 1.png", class: "center-block", alt: "funcionarios", width: "50%") %>
                    <%= link_to("Pedidos", pedidos_path, type: "button", class:"btn btn-primary btn-block") %>
                  </div>
                </div>
              </div>
            </div>

            <div class="table-responsive">
              <table class="table table-striped table-bordered table-hover">
                <tbody>
                  <tr>
                    <td><%= label_tag(nil, "Quantidade de fornecedores:") %></td>
                    <td><%= label_tag(nil, Fornecedor.all.count) %></td>
                  </tr>
                  <tr>
                    <td><%= label_tag(nil, "Quantidade de produtos:") %></td>
                    <td><%= label_tag(nil, Produto.all.count) %></td>
                  </tr>
                  <tr>
                    <td><%= label_tag(nil, "Quantidade de clientes:") %></td>
                    <td><%= label_tag(nil, Cliente.all.count) %></td>
                  </tr>
                  <tr>
                    <td><%= label_tag(nil, "Quantidade de pedidos:") %></td>
                    <td><%= label_tag(nil, Pedido.all.count) %></td>
                  </tr>
                </tbody>
              </table>
            </div>

          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/main/login.html.erb
<html>
  <head>
    <title>Login</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <!--<link rel="stylesheet" href="style.css" type="text/css"/>-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js" type="text/javascript"></script>

  </head>
  <body>
    <div class="panel panel-primary">
      <div class="panel-heading">RD Controle de Estoque</div>
      <div class="panel-body">
        <div class="row">
          <div class="col-sm-10">
            <div class="panel panel-default">
              <div class="well" id="usuarioWell">Informe seus dados</div>
              <label id="warningLabel" style="margin-left: 10px;"></label>

              <div class="row">

                <div class="col-md-3">
                  <div class="well well-sm">
                    <!--<form onsubmit="return login">-->
                      <div class="form-group">
                        <br>
                        <select  class="form-control" name ="sexo" required>
                          <!--<option value="" selected disabled>Selecione Vínculo</option>-->
                          <option value="funcionário">Funcionário</option>
                          <option value="suporte">Suporte</option>
                        </select>
                      </div>
                      <div class="form-group">
                        <option value="" selected disabled>Nome de Usuário</option>
                        <input type="charset" class="form-control" id="user_field" name="user" required>
                      </div>

                      <div class="form-group">
                        <option value="" selected disabled>Digite sua Senha</option>
                        <input type="password" class="form-control" id="password_field" name="passcode" required>
                      </div>

                      <%= button_tag("Login", id: "login_button", class: "btn btn-primary btn-block") %>
                      <!--<%= link_to("Login", main_index_path, type: "button", class: "btn btn-primary btn-block") %>-->

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>