config/routes.rb
Rails.application.routes.draw do
  resources :pedidos
  root 'main#login'
  resources :produtos
  resources :fornecedores
  resources :clientes
  get 'main/login'
  get 'main/index'
  get '/login', :to => redirect('main/login')
  get '/index', :to => redirect('main/index')
  get 'main/verifica_usuario'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pedido.rb
class Pedido < ApplicationRecord
  belongs_to :cliente
  belongs_to :produto
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :set_pedido, only: [:show, :edit, :update, :destroy]

  # GET /pedidos
  # GET /pedidos.json
  def index
    @pedidos = Pedido.all
  end

  # GET /pedidos/1
  # GET /pedidos/1.json
  def show
    @clientes = Cliente.all
    @produtos = Produto.all
  end

  # GET /pedidos/new
  def new
    @pedido = Pedido.new
    @clientes = Cliente.all
    @produtos = Produto.all
  end

  # GET /pedidos/1/edit
  def edit
    @clientes = Cliente.all
    @produtos = Produto.all
  end

  # POST /pedidos
  # POST /pedidos.json
  def create
    @pedido = Pedido.new(pedido_params)

    produto = Produto.find_by_id(@pedido.produto.id)
    produto.quantidade -= @pedido.quantidade

    produto.save()

    respond_to do |format|
      if @pedido.save
        format.html { redirect_to @pedido, notice: 'Pedido criado com sucesso.' }
        format.json { render :show, status: :created, location: @pedido }
      else
        format.html { render :new }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pedidos/1
  # PATCH/PUT /pedidos/1.json
  def update
    respond_to do |format|
      if @pedido.update(pedido_params)
        format.html { redirect_to @pedido, notice: 'Pedido atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @pedido }
      else
        format.html { render :edit }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedidos/1
  # DELETE /pedidos/1.json
  def destroy
    @pedido.destroy
    respond_to do |format|
      format.html { redirect_to pedidos_url, notice: 'Pedido deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_pedido
    @pedido = Pedido.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def pedido_params
    params.require(:pedido).permit(:codigo, :quantidade, :cliente_id, :produto_id)
  end
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/views/pedidos/_form.html.erb
<%= form_for(@pedido, html: { class: "form-horizontal", role: "form" }) do |f| %>
    <% if @pedido.errors.any? %>
        <div class="alert alert-danger alert-dismissable" role="alert">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4><%= pluralize(@pedido.errors.count, "error") %> prohibited this pedido from being saved:</h4>

          <ul>
            <% @pedido.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <label class="col-sm-2 control-label" for="pedido_codigo">Código</label>
      <div class="col-sm-10">
        <%= f.number_field :codigo, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :cliente, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.collection_select(:cliente_id, @clientes, :id, :razaoSocial) %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :produto, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.collection_select(:produto_id, @produtos, :id, :nome) %>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label" for="pedido_quantidade">Quantidade</label>
      <div class="col-sm-10">
        <%= f.number_field :quantidade, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit class: "btn btn-primary", value: "Salvar pedido", 'data-disable-with': "Salvando pedido" %>
      </div>
    </div>
<% end %>

app/views/pedidos/edit.html.erb
<div class="page-header">
  <%= link_to pedidos_path, class: 'btn btn-default' do %>
      <span class="glyphicon glyphicon-list-alt"></span>
      Voltar
  <% end %>
  <%= link_to @pedido, class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-info-sign"></span>
      Exibir
  <% end %>
  <h1>Editar pedido</h1>
</div>

<%= render 'form' %>

app/views/pedidos/index.html.erb
<div class="page-header">
  <%= link_to new_pedido_path, class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-plus"></span>
      Novo Pedido
  <% end %>
  <h1>Lista dos pedidos</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
      <th>Código</th>
      <th>Quantidade</th>
      <th>Cliente</th>
      <th>Produto</th>

      <th></th>
    </tr>
    </thead>

    <tbody>
    <%= content_tag_for(:tr, @pedidos) do |pedido| %>
        <td><%= pedido.codigo %></td>
        <td><%= pedido.quantidade %></td>
        <td><%= pedido.cliente.razaoSocial %></td>
        <td><%= pedido.produto.nome %></td>

        <td><%= link_to 'Exibir', pedido %></td>
    <% end %>
    </tbody>
  </table>
</div>

app/views/pedidos/new.html.erb
<div class="page-header">
  <%= link_to pedidos_path, class: 'btn btn-default' do %>
      <span class="glyphicon glyphicon-list-alt"></span>
      Voltar
  <% end %>
  <h1>Novo pedido</h1>
</div>

<%= render 'form' %>

app/views/pedidos/show.html.erb
<div class="page-header">
  <%= link_to pedidos_path, class: 'btn btn-default' do %>
      <span class="glyphicon glyphicon-list-alt"></span>
      Voltar
  <% end %>
  <%= link_to edit_pedido_path(@pedido), class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-pencil"></span>
      Editar
  <% end %>
  <h1>Exibir pedido</h1>
</div>

<dl class="dl-horizontal">
  <dt>Código:</dt>
  <dd><%= @pedido.codigo %></dd>

  <dt>Quantidade:</dt>
  <dd><%= @pedido.quantidade %></dd>

  <dt>Cliente:</dt>
  <dd><%= @pedido.cliente.razaoSocial %></dd>

  <dt>Produto:</dt>
  <dd><%= @pedido.produto.nome %></dd>

</dl>