config/routes.rb
Rails.application.routes.draw do
  resources :pedidos
  root 'main#login'
  resources :produtos
  resources :fornecedores
  resources :clientes
  get 'main/login'
  get 'main/index'
  get '/login', :to => redirect('main/login')
  get '/index', :to => redirect('main/index')
  get 'main/verifica_usuario'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/produto.rb
class Produto < ApplicationRecord
  belongs_to :fornecedor
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
    @fornecedores = Fornecedor.all
  end

  # GET /produtos/1/edit
  def edit
    @fornecedores = Fornecedor.all
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto criado com sucesso.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:codigo, :nome, :fornecedor_id, :quantidade)
    end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<%= form_for(@produto, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @produto.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@produto.errors.count, "error") %> prohibited this produto from being saved:</h4>

      <ul>
      <% @produto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label class="col-sm-2 control-label" for="produto_codigo">Código</label>
    <div class="col-sm-10">
      <%= f.number_field :codigo, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :nome, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nome, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :fornecedor, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <!--<%= f.text_field :fornecedor, class: "form-control" %>-->
      <%= f.collection_select(:fornecedor_id, @fornecedores, :id, :razaoSocial) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :quantidade, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :quantidade, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary", value: "Salvar produto", 'data-disable-with': "Salvando produto" %>
    </div>
  </div>
<% end %>

app/views/produtos/edit.html.erb
<div class="page-header">
  <%= link_to produtos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to @produto, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Exibir
  <% end %>
  <h1>Editando produto</h1>
</div>

<%= render 'form' %>

app/views/produtos/index.html.erb
<div class="page-header">
  <%= link_to new_produto_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Novo produto
  <% end %>
  <h1>Lista dos produtos</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Código</th>
        <th>Nome</th>
        <th>Fornecedor</th>
        <th>Quantidade</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @produtos) do |produto| %>
        <td><%= produto.codigo %></td>
        <td><%= produto.nome %></td>
        <td><%= produto.fornecedor.razaoSocial %></td>
        <td><%= produto.quantidade %></td>

        <td><%= link_to 'Exibir', produto %></td>
        <td><%= link_to 'Editar', edit_produto_path(produto) %></td>
        <td><%= link_to 'Deletar', produto, method: :delete, data: { confirm: 'Tem certeza disso?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/produtos/new.html.erb
<div class="page-header">
  <%= link_to produtos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h1>Novo produto</h1>
</div>

<%= render 'form' %>

app/views/produtos/show.html.erb
<div class="page-header">
  <%= link_to produtos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to edit_produto_path(@produto), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h1>Exibir produto</h1>
</div>

<dl class="dl-horizontal">
  <dt>Código:</dt>
  <dd><%= @produto.codigo %></dd>

  <dt>Nome:</dt>
  <dd><%= @produto.nome %></dd>

  <dt>Fornecedor:</dt>
  <dd><%= @produto.fornecedor.razaoSocial %></dd>

  <dt>Fornecedor:</dt>
  <dd><%= @produto.quantidade %></dd>

</dl>